[tox]
envlist =
    py310-pandas150-requests231
    py310-pandas200-requests231
    py310-pandas220-requests232
skip_missing_interpreters = true

[testenv]
usedevelop = true
basepython = python3.10
deps =
    pytest

[testenv:py310-pandas150-requests231]
deps =
    {[testenv]deps}
    numpy==1.23.5
    pandas==1.5.3
    requests==2.31.0
commands = pytest tests/

[testenv:py310-pandas200-requests231]
deps =
    {[testenv]deps}
    numpy==1.24.4
    pandas==2.0.3
    requests==2.31.0
commands = pytest tests/

[testenv:py310-pandas220-requests232]
deps =
    {[testenv]deps}
    numpy==1.26.4
    pandas==2.2.2
    requests==2.32.4
commands = pytest tests/
